package com.acme.doktoric;

import com.acme.doktoric.exceptions.UnsupportedRequestTypeException;

import java.io.IOException;


/**
 * Generated by Doktoric
 */
public class EntryPoint {

    private static PortApp portApp;

    public static void main(String[] args) throws IOException, UnsupportedRequestTypeException {
        portApp=new PortApp();
    }

}
